### ISSUE TITLE
Homework screen for send sms of homework

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SGS#145]

**Comment by serviceproviderpk** [comment]
@tariqmtoor  provide some detail about this please

**Comment by tariqmtoor** [comment]
i think sending home work via sms is not a good way. 
sirf ye sms jana chaihay k:

Please Visit "www.starshighschool.edu.pk/parentsportal" for Home work and otherreports of your child.

website address editable ho ga. ta k her institute apni site ka address type kr skay.
