### ISSUE TITLE
11-November-18

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#176]

**Comment by adilshehbaz** [comment]
1.	Super Admin Account: Contract Defaulter List myn  ACTIVE / INACTIVE BRANCHES alg alg show kryn. SMS b Active/Inactive Branches ko alehda alehda he send hoon.

**Comment by adilshehbaz** [comment]
![image](https://user-images.githubusercontent.com/28675602/47949075-c9c74600-df5e-11e8-8211-75f3280cd59b.png)

**Comment by adilshehbaz** [comment]
![image](https://user-images.githubusercontent.com/28675602/47949079-d350ae00-df5e-11e8-86e1-b4c69f94e8c2.png)

**Comment by adilshehbaz** [comment]
![image](https://user-images.githubusercontent.com/28675602/47949080-dd72ac80-df5e-11e8-96e4-8ac39c1ef254.png)

**Comment by adilshehbaz** [comment]
![image](https://user-images.githubusercontent.com/28675602/47949089-f5e2c700-df5e-11e8-959d-be6633954aa0.png)

**Comment by adilshehbaz** [comment]
6.	Fee Generate Grid, Fee Collection, Test record Management, Contract etc Grids are not showing Data.

**Comment by adilshehbaz** [comment]
7.	Plz Add (_StudentName_) & (_Balance_) Options in DEFAULTER SMS. User may add them in text box according to the need.

**Comment by adilshehbaz** [comment]
8.	Fee Collection Report?????????????

**Comment by adilshehbaz** [comment]
9.	Remove FEE COLLECTION IN INSTALMENT from Menu.

**Comment by adilshehbaz** [comment]
10.	  Branch Admin must delete the fee entry.

**Comment by adilshehbaz** [comment]
11.	  In DAY BOOK Menu, Sort & Rename Menu Items as;	
a.	 Define Category
b.	Day Book Entry
c.	Day Book Report
*Note: A Combine Report of Revenue & Expenses also required.

**Comment by adilshehbaz** [comment]
12.	 Replace “Test Record Management” to “Enter Test Result”.

**Comment by adilshehbaz** [comment]
13.	 Add a Button “Enter Test result” on this screen.

**Comment by adilshehbaz** [comment]
14.	 Don’t show a long list of accounts on adding a staff. Show only FEE Account to check/uncheck

**Comment by adilshehbaz** [comment]
15.	 Search for branches on all screens for super admin.

**Comment by adilshehbaz** [comment]
16.	 Result Report on “Students Profile”.

**Comment by adilshehbaz** [comment]
**2- Fixed**

**Comment by adilshehbaz** [comment]
**9- Fixed**

**Comment by adilshehbaz** [comment]
**11- Fixed**

**Comment by adilshehbaz** [comment]
**12- Fixed**

**Comment by adilshehbaz** [comment]
**13- Fixed**
