### ISSUE TITLE
Issues November 5 to 10

### ISSUE THREAD

**Issue by zaifullah786** [serviceproviderpk/SGS#177]
**1)** Biomatric staff report ka jo formate send kia hai us k mutabik bna dain

**2)** Jab staff apni atendence k liay thumb lagay to attendence k foran bad usay popup message show ho thanks ka ya koi beep ta k usay pata chal jay k attendence lag gai hai, current situation main staff ko pata nai chalta or wo phir thumb laga daitay hn

**3)** Sms event bnana hai jis main attendence in pay msg jay ga or out pay jay ga or yah right admin k pass ho ga k dono pay bhaijna hai ya kisi aik pay.

**4)** Exam ki 2 new report bnani aik single student or aik class wise jis main wo subject optional select kray ga or bs un he subject ki report show krway

**Comment by adilshehbaz** [comment]
Exam ki 2 new report bnani aik single student or aik class wise jis main wo subject optional select kray ga or bs un he subject ki report show krway
**Fixed**

**Comment by adilshehbaz** [comment]
**1, 3,4 Fixed**
