### ISSUE TITLE
Option To Send Branch Document  and Syllabus with Permission.

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SGS#181]
1- Need a screen to send documents to branches for super admin
2- We can share one document with single branch, multi or whole organization.
3- Document download option on the given date

**Comment by serviceproviderpk** [comment]
Solution:
Who will send? ORG

Acces Date 

ORG > Branch

**Comment by serviceproviderpk** [comment]
Lookup, Document Type,

Documents
DocumentAssignments

**Comment by serviceproviderpk** [comment]
AvailableDocuments,
ExpiredDocuments
