### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SGS#201]
1) on login i entered wrong password got this msg.
![image](https://user-images.githubusercontent.com/19146254/49419786-3c1f8600-f7aa-11e8-92c0-4344b8f487ff.png)

**Comment by serviceproviderpk** [comment]
2) remove this logo 
![image](https://user-images.githubusercontent.com/19146254/49419835-7b4dd700-f7aa-11e8-8fff-3f5f8561a0e6.png)

**Comment by serviceproviderpk** [comment]
3) sort brnanches in dropdown with name
![image](https://user-images.githubusercontent.com/19146254/49419973-0f1fa300-f7ab-11e8-9d38-16bccc3a3dc6.png)

**Comment by serviceproviderpk** [comment]
4) show latest on top
![image](https://user-images.githubusercontent.com/19146254/49420023-4e4df400-f7ab-11e8-9bd2-e5560d25a7df.png)

**Comment by serviceproviderpk** [comment]
5)
i didnot choose any branch and click on submit it is handed.
![image](https://user-images.githubusercontent.com/19146254/49420195-172c1280-f7ac-11e8-81db-4bbdd846128c.png)

**Comment by serviceproviderpk** [comment]
6) Document history tab

**Comment by zaifullah786** [comment]
RFR(1,2,3,4,5,6)
