### ISSUE TITLE
Super Admin Reports

### ISSUE THREAD

**Issue by maazsagi** [serviceproviderpk/SGS#224]
Four Reports for Super Admin
Attendance Summary Individual
All Campus Attendance Summary
Fee Collection Report
All Campuses Fee Collection Report

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test Attendance Summary Individual 
All Campus Attendance Summary Added in Manage Attendence Menu

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Menu myn add krnay ka kis nay kaha????????? ye super admin report hay sirf super admin ko he show honi chahiay.
Client branch ko shak b nahi hona chahiay k humari reports ko view kia ja rha hay. Hum nay apny branches say royalty laini hoti hay. 
Plz Remove this menu asap. & keep in mind the point next time

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test
