### ISSUE TITLE
Branches Agreement

### ISSUE THREAD

**Issue by maazsagi** [serviceproviderpk/SGS#230]
Changes in Branch Agreement and its Design

**Comment by tariqmtoor** [comment]
Agreement ok hay sirf Format kr dyn usay

**Comment by nawabanjum** [comment]
@tariqmtoor  please elaborate more.

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
![WhatsApp Image 2019-08-20 at 1 47 04 PM](https://user-images.githubusercontent.com/29690582/63335181-57411e80-c356-11e9-9078-c0960e38a41d.jpeg)

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
2 pages per aa rha hay page setting k bawajood. Plz set it on 1 age

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir if it is ok then close this point thanks
