### ISSUE TITLE
Admin Account for specific Branches

### ISSUE THREAD

**Issue by maazsagi** [serviceproviderpk/SGS#236]
New admin account to only view reports

**Comment by tariqmtoor** [comment]
@serviceproviderpk @nawabanjum 
Parent/Child Account for Reports such as:
Fee Report/ Attendance etc

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @nawabanjum 
This account is required for an owner If he have 3 or more  schools and asks for a master account to check reports of all 3 schools

**Comment by tariqmtoor** [comment]
@Hammadshahid170 

![WhatsApp Image 2019-08-20 at 1 47 04 PM](https://user-images.githubusercontent.com/29690582/63332910-e566d600-c351-11e9-8d6d-acd5776b3d91.jpeg)

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
[Template for super admin.pdf](https://github.com/serviceproviderpk/SGS/files/3519850/Template.for.super.admin.pdf)

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test assign which  branches to any person then he can see reports which branches assigned

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Branches assign ho rahi hyn. Laken jis bnday ko assign krni hyn usay sirf VIEW k Rights deny hyn. Edit/del k nahi.
Aur ooper walay Commints myn aik report share ki hui hay wo report b bnani hay

**Comment by nawabanjum** [comment]
@tariqmtoor  View k rights ap khud set krn gy ,baqi report hum bna dty hn ,
aur ye report kahan show krwani h ?

**Comment by tariqmtoor** [comment]
Jahan ap munasib samjhyn. 
meray khyal myn BRANCH Select krnay ki option  sath iss report ka button laga dyn

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test
