### ISSUE TITLE
Result Card

### ISSUE THREAD

**Issue by maazsagi** [serviceproviderpk/SGS#238]
Result Card Printing

**Comment by tariqmtoor** [comment]
[Academic Performance Performa (1).pdf](https://github.com/serviceproviderpk/SGS/files/2868243/Academic.Performance.Performa.1.pdf)

**Comment by tariqmtoor** [comment]
Plz Add Student Pic in this result card

**Comment by tariqmtoor** [comment]
Waiting for this

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by nawabanjum** [comment]
On test result screen http://starsschool.campusmanager.biz/TestSystem/Index
use Exam type and remove annual *Manage annual result link*.
Exam type lookup remove session drop down only

**Comment by nawabanjum** [comment]
@tariqmtoor  please test this report on Start school and give your feedback if any

**Comment by tariqmtoor** [comment]
@nawabanjum  Excellent Janab
Just a little formatting required
![Untitled](https://user-images.githubusercontent.com/29690582/58087630-5c1cf780-7bda-11e9-95cd-6d2c3d9682f2.png)

**Comment by tariqmtoor** [comment]
@nawabanjum 
Poori class ki report laini ho tu????????
Date Range ???????????????

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by nawabanjum** [comment]
local fixed

**Comment by tariqmtoor** [comment]
@nawabanjum 
![1](https://user-images.githubusercontent.com/29690582/59024295-15323180-886b-11e9-8d86-fdc814a38deb.jpg)

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by tariqmtoor** [comment]
@nawabanjum 
Aik say zayada student select krnay per Report PRINTING ki setting theek nhi hay

**Comment by nawabanjum** [comment]
@tariqmtoor  please check

**Comment by tariqmtoor** [comment]
@nawabanjum @serviceproviderpk @Hammadshahid170 
![2](https://user-images.githubusercontent.com/29690582/60797283-6d20c880-a188-11e9-8a6d-747d7dc897b0.jpg)

**Comment by Hammadshahid170** [comment]
@tariqmtoor sir please test
