### ISSUE TITLE
3 - Defaulter By Account

### ISSUE THREAD

**Issue by maazsagi** [serviceproviderpk/SGS#239]
Defaulter Student with Account Name

**Comment by tariqmtoor** [comment]
28 Jan ko open kia aur aj March ki 2 hay. I appreciate the speed

**Comment by tariqmtoor** [comment]
Still waiting for this

**Comment by tariqmtoor** [comment]
@nawabanjum 
![Untitled](https://user-images.githubusercontent.com/29690582/58540541-03b9ab80-8213-11e9-9f92-5ee0471bc107.png)

**Comment by nawabanjum** [comment]
@tariqmtoor  this report will never be show the correct data **Defaulter By Account #239** because while receiving the fee , we are not entering the amount with specified account.
If you have any logic let me know please.

**Comment by tariqmtoor** [comment]
@nawabanjum, 
Other Dues Add krtay huay ya New Student enroll krtay huay jab Fee, Admission Fee etc myn receivables daal detay hyn tu wo receivables Defaulters myn by account show honay chahiayn

**Comment by tariqmtoor** [comment]
@nawabanjum @serviceproviderpk 
Plz activate this report
