### ISSUE TITLE
Group Rights Screen

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#252]
Flow of user rights

**Comment by serviceproviderpk** [comment]
i created a group with name "Junior Staff" given some rights

a) he can see the things those were not assigned to him
b)  assinged menu not visible for him

![image](https://user-images.githubusercontent.com/19146254/53690390-78ec2080-3d8b-11e9-96ba-00805fa4297f.png)

then assigned to staff "js@js.com"

@sppk please check it and fix asap.

**Comment by adilshehbaz** [comment]
**RFR**

**Comment by tariqmtoor** [comment]
[Rights.xlsx](https://github.com/serviceproviderpk/SGS/files/2937852/Rights.xlsx)

**Comment by tariqmtoor** [comment]
New Branch create honay per by default STAFF GROUP ko ooper di gaui list k mutabiq rights assign honay chahyan.

**Comment by TahirHussai** [comment]
This Task is  80% completed. We will complete it in comming week InshAllah.

**Comment by serviceproviderpk** [comment]
Flow of User Rights

in all domains we have one link to manage "System available Rights"

/SystemSettings/ManageSystemRight/Index

we have added Profile type for each Rights(screen)

Main organization
Main Branch
Staff
for each screen/rights

if profile type is Staff=3
this screen will be available to Staff, Branch and Organization

if profile type is Staff = 2
this screen will be available to Branch and Organization

if profile type is Staff = 1
this screen will be available to Organization

@tariqmtoor  @adilshehbaz  @nawabanjum

**Comment by serviceproviderpk** [comment]
ready for testing.
