### ISSUE TITLE
Send SMS on LOGIN

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#254]
koi b staff ya branch jab login ho tu us k cell per sms jana chahiay k
"(_staff_) is Login to Campus Manager"

**Comment by sppk** [comment]
RFR

**Comment by nawabanjum** [comment]
@tariqmtoor  please test it.

**Comment by tariqmtoor** [comment]
Sirf sms krna tha k u r logged in. 
Code wala process nhi krna. 10 min say code ka wait kr rha hoon. Abhi tk nhi aya. Aisay tu kaam mushkil ho jayga
