### ISSUE TITLE
Format the Certificates

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#255]
Character Certificate, School Leaving Certificate & Admission Form ko format krnay ka kaha tha, & in k sample b diay thay. Plz formate them

**Comment by tariqmtoor** [comment]
School Leaving Certificate is Ok but
Character Certificate DATA fetch nhi kr rha

**Comment by nawabanjum** [comment]
@tariqmtoor  I tested it on starSchool domain and working fine on School demo,kinldy write down the step s ,when it is not working and on which domain

**Comment by nawabanjum** [comment]
please check

**Comment by tariqmtoor** [comment]
Passed Out Students myn Character Certificate ka data Fetch nhi ho rha
Strucked Off Studennts myn School Leaving Ok hy.
Manage Student Grid myn Registration Form ko b formatting ki zarorat hy

**Comment by nawabanjum** [comment]
**Manage Student Grid myn Registration Form ko b formatting ki zarorat hy** 
@tariqmtoor  regarding formatting please send us design as you uploaded on Result card design.

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by tariqmtoor** [comment]
@nawabanjum 
certificates formates kal share kron ga

**Comment by tariqmtoor** [comment]
@nawabanjum 
Registration Form
"http://starsschool.campusmanager.biz/MyReporting/StudentRegistrationForm?id=16704"

[20190521.pdf](https://github.com/serviceproviderpk/SGS/files/3201504/20190521.pdf)

**Comment by tariqmtoor** [comment]
@nawabanjum 
Formate of Character & Schoole Leaving Certificates

![Uploading SL Certificate.jpg…]()

**Comment by tariqmtoor** [comment]
@nawabanjum 
Formates of School Leaving & Character Certificates
![School Leaving Certificate](https://user-images.githubusercontent.com/29690582/58081957-71d8ef80-7bcf-11e9-8ab9-d31ee4a6970f.png)
![Character Certificate](https://user-images.githubusercontent.com/29690582/58081958-71d8ef80-7bcf-11e9-9aa4-bbcc6894e624.png)

**Comment by nawabanjum** [comment]
@tariqmtoor  Please test

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by tariqmtoor** [comment]
A little Format is required in REASON OF LEAVING SCHOOL wali line

**Comment by nawabanjum** [comment]
@tariq bhai please test

**Comment by tariqmtoor** [comment]
@nawabanjum @serviceproviderpk 
bhai iss point ny tu pagal he kr k rakh dya hay. 
CHARACTER CERTIFICATE kaha gya ab. Scl Leaving certificate he show ho rha hay dono jagga per

**Comment by nawabanjum** [comment]
@tariqmtoor  please test
