### ISSUE TITLE
Day Book Reports

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#256]
Day Book Reports not working fine. Revenue & Expenses Ok hyn But Overall report myn Data theek nhi ata. Aur Fee automatically Revenue report myn ani chahiay

**Comment by serviceproviderpk** [comment]
@adilshehbaz  test it properly.
as you fixed it, record video or simple text  to explain how it will work.

**Comment by TahirHussai** [comment]
Fixed on all domains

**Comment by serviceproviderpk** [comment]
Yes fixed on all domains
