### ISSUE TITLE
Customer Support

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SGS#258]
1) we need customer support code in website.
that will help us, which user is get the issue.

we will ask for code and will work on his issue instead of asking 
what is your email, what is your password, what is your branch name etc.

2) for each customer dashboard show Customer code
3) Find details by Customer code

**Comment by serviceproviderpk** [comment]
4) in Campus Manager add button "Customer Support"
customer will enter  his code and issue detail and submit.
5) admin will set priority for it. developer will work according to the priority

and link of github also shared for details of issue.

**Comment by serviceproviderpk** [comment]
5) Manage Customer Support

Add+edit

Search by : Status | Priroty

**Comment by TahirHussai** [comment]
As Per Yesterday Discussion database table is updated please check now.

**Comment by serviceproviderpk** [comment]
1) edit screen must be inside dashboard
2)  in list page show  (SNO,IssueDate,Priority,Status,Description  "Edit"
3) in edit screen show  Dropdownss for required fields.

**Comment by TahirHussai** [comment]
edit screen must be inside dashboard
in list page show (SNO,IssueDate,Priority,Status,Description "Edit"
in edit screen show Dropdownss for required fields
RFR
