### ISSUE TITLE
Delete brnach

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SGS#259]
we created a test branch, we need to remove this branch and data associated related to this branch.
branch name testesttest

**Comment by tariqmtoor** [comment]
In School Domain

**Comment by nawabanjum** [comment]
Branch deletion done with Admin login.if another role has rights to delete this, then need to show list of delete request branch for the admin review where admin will delete branch from the list.

**Comment by nawabanjum** [comment]
@tariqmtoor  please check

**Comment by adilshehbaz** [comment]
Please check .
