### ISSUE TITLE
ManagePrifleTypes

### ISSUE THREAD

**Issue by TahirHussai** [serviceproviderpk/SGS#260]
create a new controll "ManagePrifleTypes"
show  add/edit and list of ProfileTypes

2) Create new controller MaangeXRecords

in this page show list of employe.

**Comment by TahirHussai** [comment]
create a new controll "ManagePrifleTypes"
show add/edit and list of ProfileTypes

                              "RFR"

**Comment by serviceproviderpk** [comment]
Thanks,
