### ISSUE TITLE
Fee Voucher

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#262]
Fee Voucher creation is too difficult. Vouchers k liay main menu myn GENERATE FEE k neechay New Menu bna dyn. Jiss student ka jitna balance Defaulter list myn show ho rha ho utna us k voucher myn show ho jay. Voucher Creation k waqat Due Date Manually enter honi chahiay & partial payment ki b ijazat honi chahiay

**Comment by tariqmtoor** [comment]
Family Voucher theek kam nhi kr rha

**Comment by tariqmtoor** [comment]
Family Fee Collection b kaam nhi kr rha

**Comment by adilshehbaz** [comment]
**Family Voucher Created**

**Comment by adilshehbaz** [comment]
@tariqmtoor please check,if is there any improvement needed please let  us know with flow.

**Comment by tariqmtoor** [comment]
Shows errore screen

**Comment by nawabanjum** [comment]
![Capture](https://user-images.githubusercontent.com/16934768/56352280-518cce00-61e8-11e9-8793-62790346d214.PNG)
@tariqmtoor  bhai is working on [](http://starsschool.campusmanager.biz/) please mention the details where this report is not working ,

**Comment by tariqmtoor** [comment]
Stars School Suchyari Branch per check kia
6th Class Boys Section ki defaulter list myn Balance Kuch aur hy laken jab VOUCHER Print krtay hyn tu voucher per balance kuch aur print ho rha hay. 
Also checked on other classes. same issue

**Comment by nawabanjum** [comment]
@tariqmtoor  please check on Start school domain and let me know if any changes required
