### ISSUE TITLE
15 days trial

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SGS#263]
1) exam report'2
) show max report

**Comment by tariqmtoor** [comment]
DayBook
Exams Report
Send General SMS

ye options load nhi hoti trial account per

**Comment by serviceproviderpk** [comment]
@tariqmtoor 
Please check now. if not fixed please add your comments

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by tariqmtoor** [comment]
Exams Reports show nhi ho rahi abhi trial accounts per
