### ISSUE TITLE
Class in Auto Search

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#270]
Please CONCATENATE "Class" with Student Name & Father Name in AutoSearch

**Comment by nawabanjum** [comment]
Locally added in Fee receipt and student Profile

**Comment by tariqmtoor** [comment]
i will check when released

**Comment by nawabanjum** [comment]
**Fixed**

**Comment by tariqmtoor** [comment]
Plz concatenation ki tarteeb you rkhyn
**Fee Screen**: 
Students Name + Father Name + Class + (Active Student)
**Other Screens** just as Auto search in Manager Student, Student Profile Search etc
Students Name + Father Name + Class

**Comment by nawabanjum** [comment]
@tariqmtoor  Please test on Star School domain and let me know if it is OK,so that i can apply on All the Screen

**Comment by nawabanjum** [comment]
Please check
