### ISSUE TITLE
Branch Summary on DASH BOARD

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#271]
Branch Summary Dash board say miss ho gai hay Plz re-add it. Date From & Date to by default same day ho. For Example 26-03-2019 to 26-03-2019.
It means k by default aik din ki summary show ho rhai ho.

2 filed add krni hy summary myn.

* Numbers of defaulters till today................
* Receivable amount from defaulters.............

**Comment by adilshehbaz** [comment]
@tariqmtoor  please cheeck
