### ISSUE TITLE
CONTARCT SMS ISSUE

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#274]
Contract walay SMS ko enable/disable krnay pr koi farq nhi parta. Msg off krnay per b msg deliver hon jaty hyn.

1st April ko bill generate krnay hyn. plz isi release myn fix kr dijiay ga

**Comment by nawabanjum** [comment]
Fixed

**Comment by adilshehbaz** [comment]
Fixed Please check.

**Comment by tariqmtoor** [comment]
OKK
