### ISSUE TITLE
Parents Portal for Cantab

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#276]
Plz add a Link of Parents Portal for schools of Cantab domain in campusmanager.biz. Logo is attached
![cantab logo](https://user-images.githubusercontent.com/29690582/55550681-4159f680-56f2-11e9-88e0-d2e74f8c1fd1.png)

**Comment by adilshehbaz** [comment]
Done Please check

**Comment by tariqmtoor** [comment]
Working

**Comment by tariqmtoor** [comment]
Good
