### ISSUE TITLE
Changing of Text of SMS Events

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#278]
Plz change the sms titles as given in pic
![Untitled](https://user-images.githubusercontent.com/29690582/56202984-b2d46600-605d-11e9-862d-2fb775721de5.png)

**Comment by nawabanjum** [comment]
Fixed live

**Comment by tariqmtoor** [comment]
School and academy ki domain per fix kia hy ap ny.
College. United. Software. Cantab
In 4 domains per b fix krn

**Comment by nawabanjum** [comment]
**Fixed**
