### ISSUE TITLE
Fee Reports Error

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#279]
Fee Collection Report & Individual Fee Collection Report ka Data same nhi aa rha.
STARS SCHOOL DOMAIN Per Suchyari Branch 
17 April say 17 April tak Fee Collection Report Total Collection 22200/- show kr rhai hay
jbk Individual Collector Report 24700/- Show kr rhi hay.

Software Domain per ye report load he nhi ho rhi.

**Comment by nawabanjum** [comment]
@tariqmtoor  i'm debugging

**Comment by nawabanjum** [comment]
**Fixed**
