### ISSUE TITLE
Feedback April 192019

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SGS#280]
1)  Allow mark attendance with out selecting section OR multi selection of section
3) on  mark attendance remove  "Default" statuses of attendance.

**Comment by tariqmtoor** [comment]
Result report of class without selection of section required.
Result entry is not issue

**Comment by nawabanjum** [comment]
Please check the attendance,for result i'm working on this

**Comment by tariqmtoor** [comment]
Attendance is OKK

**Comment by nawabanjum** [comment]
@tariqmtoor  I have spend the 1 hour on it ,and realize that this report take more then 1 day ,its not easy task we need to redesign all the html and code flow.

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by tariqmtoor** [comment]
Overall Excellent. 
A Little error occured
![Untitled](https://user-images.githubusercontent.com/29690582/57195794-0ad0ff00-6f70-11e9-8211-c094515e5583.png)

**Comment by nawabanjum** [comment]
@tariqmtoor  please check

**Comment by tariqmtoor** [comment]
Everything is fine Sir. Just a little formatting is needed. 
![Untitled](https://user-images.githubusercontent.com/29690582/57278143-2a2a7200-70bf-11e9-8a0b-f955073f343d.png)

**Comment by nawabanjum** [comment]
@Fixed locally

**Comment by tariqmtoor** [comment]
@nawabanjum 
1. Reports Title: Student Test Report nhai blk Class Test Report hy
2. Remove Roll Number Column from Report

**Comment by nawabanjum** [comment]
@tariqmtoor  please test 

**Grid ko dark kr dyn. Print k waqat border show he nahi hota**
this is default behavior of the print view please use Color printer for this

**Comment by tariqmtoor** [comment]
@ Nawab Bhai
Award list per tu grid dark hy. Aur her koi colour printer afford b nhi kr skta

**Comment by nawabanjum** [comment]
@tariqmtoor  please check on  http://starsschool.campusmanager.biz
