### ISSUE TITLE
Very Important & Urgent Issues

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#281]
1- Staff ko register krtay waqat IN-Time & Out Time save kray
2- Staff ka USERNAME editable ho
3- Staff ki Attendance Report Present k sath Late comings, before time chhuti etc b mention kray.

**Comment by nawabanjum** [comment]
@tariqmtoor  please check

**Comment by serviceproviderpk** [comment]
@tariqmtoor  did you check it?
if any issue mension here plz, if fixed close it.
