### ISSUE TITLE
Award List Error

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#286]
Award List in all domains dont sjow data if class contain only 1 student.

2 ya 2 say zyada students per koi problem nhi hay

**Comment by nawabanjum** [comment]
@tariqmtoor  please test it on http://campusmanager.biz

**Comment by tariqmtoor** [comment]
www.campusmanager.biz
per tu AWARD LIST aur Reports show he nhi ho rhi tu check kaisay kron

**Comment by nawabanjum** [comment]
@tariqmtoor  please test
