### ISSUE TITLE
UI - /SystemSettings/ManageSystemRight/Index

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SGS#287]
/SystemSettings/ManageSystemRight/Index

we have added Profile type for each Rights(screen)

Main organization
Main Branch
Staff
for each screen/rights

if profile type is Staff=3
this screen will be available to Staff, Branch and Organization

if profile type is Main Branch= 2
this screen will be available to Branch and Organization

if profile type is Main organization= 1
this screen will be available to Organization

add instructions in create rights screen please

**Comment by nawabanjum** [comment]
Closed by nawab
