### ISSUE TITLE
Printing Fee Receipt

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#290]
Fee wasool krtay waqat agar rush ki waja say print na lay sakyn tu baad myn students ko receipts ka print dena hota hy. One by One Receipt print krna kafi hectic hy. Is it possible k One click pe reuired date ki sari receipts ka print mil jay>?

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir Please test Menu Added in FeeManagement

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Plz Rename the Menu as "Print Bulk Fee Receipts" and shift this menu at the end of Fee Reports

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
agar Family Fee Collection menu say fee wasool kryn tu bulk print wali command say 1 ki jagga 2 print nikltay hy aik receipt k
