### ISSUE TITLE
Add Other Dues Screen

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#293]
http://starsschool.campusmanager.biz/OtherDuesDetail/Index/

Plz change the method of adding other dues in students fee.

![Untitled](https://user-images.githubusercontent.com/29690582/57981673-fd2d7600-7a53-11e9-9ae0-caf60cacce26.png)

Class/Section select krnay per all students show ho jayn. Un k samnay BOX myn amount type krnay ki option ho.

**Comment by nawabanjum** [comment]
Local Fixed
