### ISSUE TITLE
Add Sr#

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#294]
http://starsschool.campusmanager.biz/AttendanceDetail/Index/

Plz add Button & Serial Number in List
![1](https://user-images.githubusercontent.com/29690582/58303900-8efa0200-7e0b-11e9-8a16-e7005915b40a.png)

**Comment by nawabanjum** [comment]
tested local

**Comment by nawabanjum** [comment]
@tariqmtoor  please check
