### ISSUE TITLE
Contact Info Report

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#297]
http://software.campusmanager.biz/MyReporting/ContactInfo?ClassId=&SectionId=
New branch create krnay per Overall Contact Info report per Error screeb aa jati hay Class + Section select krnay per nhi aati

**Comment by nawabanjum** [comment]
tested  local

**Comment by nawabanjum** [comment]
@tariqmtoor  Please test on http://starsschool.campusmanager.biz

**Comment by tariqmtoor** [comment]
This report is not working at all on SOFTWARE DOMAIN

**Comment by nawabanjum** [comment]
@tariqmtoor  Fixed on http://software.campusmanager.biz
