### ISSUE TITLE
Student I.D Card

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#298]
![aa](https://user-images.githubusercontent.com/29690582/59026353-a60b0c00-886f-11e9-885b-ef908c75d47d.png)

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test on http://software.campusmanager.biz/

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Ok hay. Baqi domains per b upload kr dyn

**Comment by Hammadshahid170** [comment]
@serviceproviderpk  sir please update on all domains
