### ISSUE TITLE
General SMS Billing

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#299]
1. Genral SMS krtay huay ap ny 2, 3 pages k sms ki option on kr di hay but billing generate krtay huay 3, 4 pages k sms ka bill nhi generate hota, sirf 1 sms ka generate hota hy.

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
Bill Generate he nahi ho raha tu check kia kron?????? Urdu SMS b enabled nhi hay

**Comment by tariqmtoor** [comment]
@nawabanjum 
![Untitled](https://user-images.githubusercontent.com/29690582/59756133-9396c680-92a2-11e9-8b1a-f9ed21ec3f2d.png)

**Comment by nawabanjum** [comment]
@tariqmtoor  please test ,we have tested it on local.

**Comment by tariqmtoor** [comment]
@nawabanjum @serviceproviderpk 
GENERAL SMS USING FILE walay sms Bill myn shamil he nahi ho rhay..............

**Comment by nawabanjum** [comment]
@tariqmtoor  please test

**Comment by nawabanjum** [comment]
@tariqmtoor  please check

**Comment by tariqmtoor** [comment]
![1](https://user-images.githubusercontent.com/29690582/60796329-96d8f000-a186-11e9-9cf3-60818c5091c6.jpg)

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
test krnay per sirf GENERAL SMS ka bill bana hay. Event walay sms bill myn shamil nahi huay

**Comment by Hammadshahid170** [comment]
Locally working

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test
