### ISSUE TITLE
Parents Portal

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#301]
Campusmanager.biz wali site per Parents Portal k button per Test information proper upload nhi ho rhi. Attendance etc theek load ho rhi hay.

Main Page per Customers Logos ki setting b theek nahi hay.

Manual/ Tutorial ka Menu add krna hay Main Page per.
[Fully Formatted PDF.pdf](https://github.com/serviceproviderpk/SGS/files/3269272/Fully.Formatted.PDF.pdf)

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test (Test information)
