### ISSUE TITLE
Staff Shift & Staff Menu

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#302]
Staff Shift ko Staff Reports k neechay Deleted Staff k ooper shift kr dyn.

STAFF SHIFT ka form fill krtay huay Brake Time, Flexibility weghaira ki options ki koi zarorat nhi,

Staff Attendance Menu ko **Staff Manual Attendance** kr dyn, Staff Salary ko **Add Staff Salary** kr dyn. Staff Reports myn BIO MATRIC ko **Biometric** kr dyn.

**Comment by Hammadshahid170** [comment]
@tariqmtoor sir please test

**Comment by tariqmtoor** [comment]
@nawabanjum 
Janab BIOMETRIC Spellings hyn

**Comment by Hammadshahid170** [comment]
Fixed

**Comment by nawabanjum** [comment]
Please test @tariqmtoor
