### ISSUE TITLE
Family Fee Collection

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#303]
Family Fee collection menu still not working correctly

**Comment by Hammadshahid170** [comment]
fixed

**Comment by nawabanjum** [comment]
Please test @tariqmtoor

**Comment by tariqmtoor** [comment]
![1](https://user-images.githubusercontent.com/29690582/60077789-2c668f80-9744-11e9-940a-4c3c146de4b1.png)

**Comment by nawabanjum** [comment]
@tariqmtoor please check

**Comment by tariqmtoor** [comment]
Not saving
![Family Fee](https://user-images.githubusercontent.com/29690582/60795400-0d74ee00-a185-11e9-91d4-02b75c2d19e7.png)

**Comment by nawabanjum** [comment]
@tariqmtoor  please check

**Comment by tariqmtoor** [comment]
@nawabanjum 
Excellent. Working Fine. Only problem is in Receipt.
![1](https://user-images.githubusercontent.com/29690582/60960786-2b2c8980-a324-11e9-98e3-c6a406d982ff.jpg)

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Abhi b error hay bhai jan. aik cnic per agar 2 ya 3 ki fee wasool ki hay tu receipt sirf last waly ki print kr rha hay. 
aik he receipt per sab bachon ki entry ho tu behter hay

**Comment by Hammadshahid170** [comment]
@nawabanjum  sir locally tested

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @nawabanjum  
1- Family Fee Collect kr k Save&Print krnay per abhi b Receipt Ghalt he print ho rahi hay.
Jbk yahi receipt baqi screens (Bulk Fee Print etc) per theek print hoti hay.

2- Family Fee receive krtay huay Father's Name search krny per agar kisi baap k 3 bachay hon tu us ka name 3 dafa aur agar kisi k 2 hon tu us ka name 2 dafa search bar myn show ho rha hota hay. Its wrong way. Bachay jitnay b hon name one time show hona chahiay

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
family fee receive krnay per aik student ki receipt 2 dafa print ho rahi hay. jbk Logoki setting b disturb ho gai hay

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Everything is ok but 2no receipts ki setting thhek nahi hay.
cutting margin wali line center myn nahi hay

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir now test plz

**Comment by Hammadshahid170** [comment]
@tariqmtoor  plz test this
