### ISSUE TITLE
2 - Day Book Report

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#304]
jo software hum pehlay use krtay thay us myn aik daily report bnti thi jis myn complete daily report ho ti thy k aj in account say paisay wasool huay hyn, in account per expense hua hay aur falan account myn itnay paisay mojod hyn.
daybook report myn CASH IN HAND report benwanay ka maqsad yahi tha but ............

**Comment by nawabanjum** [comment]
@tariqmtoor  can you please share the template of this report?

**Comment by tariqmtoor** [comment]
@nawabanjum 
[Cash Flow 08-01-16.pdf](https://github.com/serviceproviderpk/SGS/files/3549808/Cash.Flow.08-01-16.pdf)
This was the reports

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @TahirHussai 
DAYBOOK Entry k grid/Report myn Fee ko b canteen rent show kr rha hy
![1](https://user-images.githubusercontent.com/29690582/68228190-d6212b80-0016-11ea-83f8-edbc6f2ff31b.png)
 Report myn Total b add kryn

**Comment by TahirHussai** [comment]
jo software hum pehlay use krtay thay us myn aik daily report bnti thi jis myn complete daily report ho ti thy k aj in account say paisay wasool huay hyn, in account per expense hua hay aur falan account myn itnay paisay mojod hyn.
daybook report myn CASH IN HAND report benwanay ka maqsad yahi tha but
********************************************Fixed********************************************
