### ISSUE TITLE
Academic Support

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#305]
10.	ACADEMIC SUPPORT Menu per jiss account ko documents upload krnay k rights diay hoon usay Uploaded Documents view nhi hotay. Rights denay k bawajood.

**Comment by Hammadshahid170** [comment]
@tariqmtoor   sir ye issue jis domain par hy  Branch name and support code send kar den

**Comment by tariqmtoor** [comment]
@nawabanjum 
All domains

**Comment by nawabanjum** [comment]
@tariqmtoor  please test on  http://starsschool.campusmanager.biz .

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Need some discussion on this task
plz make a call to me on getting free

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test
