### ISSUE TITLE
DashBoard

### ISSUE THREAD

**Issue by Hammadshahid170** [serviceproviderpk/SGS#310]
![WhatsApp Image 2019-06-18 at 2 34 14 PM](https://user-images.githubusercontent.com/22559812/59674586-05a4d800-91dd-11e9-8c8f-9c273c6cf38a.jpeg)

**Comment by nawabanjum** [comment]
@tariqmtoor  please check

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @nawabanjum @serviceproviderpk 
DashBoard needs some formatting. Colour shler. 
Super Admin k dashboard per branch search????????

**Comment by nawabanjum** [comment]
@tariqmtoor  Please create another tasks for this.this ticket was only related to show up the classes/section summary , 
And plz mention the detail **DashBoard needs some formatting. Colour shler.
Super Admin k dashboard per branch search????????**

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @nawabanjum 
![Software Dash Boad 2019](https://user-images.githubusercontent.com/29690582/60958552-fae2ec00-a31f-11e9-89ad-ba73afa035b1.jpg)

**Comment by Hammadshahid170** [comment]
locally working

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @nawabanjum 
Stars Academy ki domain per Dashboard properly load nhi ho raha.
Class Strength show nahi hoti. baqi domains per OK hay

**Comment by nawabanjum** [comment]
@tariqmtoor  please test
