### ISSUE TITLE
Student's Enrollment in Multi Classes

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#312]
In Many Academies, they enroll students in multi classes. Such as: A students is enrolled in BA & English Language Class simultaneously. Or a student is enrolled in FSC in Subjects (Maths+Physics+English) & other student is enrolled in Chemistry+Maths only. 
How can we manage their Fee/Attendance etc in software?????

**Comment by nawabanjum** [comment]
@tariqmtoor  this is time taking task as you know by adding student in multiple overall the system flow will be change.please set the priority of others tasks , also set the low priority of this task.
