### ISSUE TITLE
Collection Summary Report

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#313]
Add a New Report in FEE REPORTS named as Collection Summary. Details of this report were discussed in meeting

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz mention some details here by @nawabanjum

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @nawabanjum 
![Collection Summary](https://user-images.githubusercontent.com/29690582/60320562-8d37d700-9993-11e9-930c-6da94a869c5d.jpg)

**Comment by Hammadshahid170** [comment]
@nawabanjum  Locally tested

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test
