### ISSUE TITLE
SMS on Login

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#315]
@serviceproviderpk @nawabanjum @
Login honay per 1 ki jagga 2 dafa sms jata hay k ap login ho gay hyn. Kuch branches per login sms jata he nahi.
I Think k LOGIN SMS ka SMS Event create kr dya jay ta k branch apni marzi say set kr skay k login per usay aur us k staff ko sms ana chahiay ya nahi.

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir Please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
LOGIN ka Msg SMS Log myn show nhai ho raha. Iss event k sms ka bill b client branch nay pay krna hay. Agar ye SMS Log myn show nahi ho ga tu bill kaisay verify kray gi client branch?????

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test
