### ISSUE TITLE
Graph on test Report

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#317]
Singke student's test report shows Graph but Multiple Students test report not showing graph. 
Graph must be there

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @nawabanjum 
Multiple Students Report myn All Students ko select krnay k bawajood sirf 18 students ka print deta hay. Class k all students ko select krnay per sab ki report print honi chahiay.....

Graph ky neechay subject name merge ho jatay hyn zayada number of tests honay per
