### ISSUE TITLE
Admission Inquiry SMS Error

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#318]
Admission Inquiry enter kr k save ki. us ka sms b chala gya. thori der baad inquiry delete kr di. SMS Log myn daikha tu us ka sms b delete ho chuka tha. ye practice bar bar ki. her dafa aisa he hua. 

i think k iss ka hal ye hay k nquiry ko delete krnay ka option khatam kr dya jay

**Comment by nawabanjum** [comment]
@tariqmtoor  please check
