### ISSUE TITLE
Add manual roll no in award list

### ISSUE THREAD

**Issue by Hammadshahid170** [serviceproviderpk/SGS#319]

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir yaha new column add karna hy ? Manual Roll# k liay 
![image](https://user-images.githubusercontent.com/22559812/61993393-c5aafd80-b084-11e9-95d3-0f493182121f.png)

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Yes.
Sr # k baad aur Student Name say pehlay........................
