### ISSUE TITLE
add manual roll no and change heading in defaulter list 

### ISSUE THREAD

**Issue by Hammadshahid170** [serviceproviderpk/SGS#320]

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir is main pehly roll# add tha ap ny hide karwa diya tha ab dubara add karna hy ?

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Janab: Student Contact Info Report, Fee Collection Reports, Award List, Result Reports sab myn Roll number add krna hay
