### ISSUE TITLE
add manual roll no in fee collection individual collector

### ISSUE THREAD

**Issue by Hammadshahid170** [serviceproviderpk/SGS#321]

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Request ki thi k 
Fee Collection Report myn jis tarah data tarteeb say aur account wise aata hay (For example: Monthly Fee, Admission fee, Test Fund), her collection ka alag column hy bilkul isi tarah INDIVIDUAL COLLECTOR REPORT myn b data column wise show ho
