### ISSUE TITLE
Fee collection and Student Registration Optimization

### ISSUE THREAD

**Issue by nawabanjum** [serviceproviderpk/SGS#322]
@tariqmtoor  I have done code optimize on both **Fee collection** and student **registration form** .
please test and verify if its working fine or  not ,if need more optimization let me know so that we can do our best effort to overcome this.
These two points took my 3 days,approximately 4 hour per day.

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir please test

**Comment by tariqmtoor** [comment]
@nawabanjum 
Mian Sab. test tay kr lia kro pehlay...............
aik student ki fee wasool krnay k baad Page refresh he nahi ho rha. Again COLLECT FEE phir ADD ka button press krnay per new student ko select krta hay.

**Comment by nawabanjum** [comment]
@tariqmtoor  as discussed on call please use a **Edge Browser** in any inconvenient.
