### ISSUE TITLE
Show Position On Single Student Test Report

### ISSUE THREAD

**Issue by nawabanjum** [serviceproviderpk/SGS#324]
1. Single Student.
2.Multiple Student 
3. Absent Student must be Shown as **A** instead of 0

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Student jis nay test na dya ho us ka result us test myn "0" show hota hay. "A" show hona chahiay.

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir locally done

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Class test Report myn tu "A" he aa rha hay but Single Student Test Report & Multiple Stu Test Report myn Abhi b "0" ee show ho rha hay. Absent stu ko sms b "Absent" jana chahiay.

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test
