### ISSUE TITLE
Add Student Screen

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#326]
Some slight changes are required in Adding Student:
1-  Student add krtay waqat ROLL NUMBER ko CLASS ROLL NUMBER.
2-  Usi Student ki Edit krtay waqat SERIAL NUMBER ki jagga CLASS ROLL NUMBER.
3-  Initial Balance jo student Add krtay waqat apply krtay hyn wo Admission Form per Account wise 
     Print krna hay

**Comment by Hammadshahid170** [comment]
@tariqmtoor sir plz test 

Also Remove Career and Set Medium Dropdown

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
3- **Initial Balance jo student Add krtay waqat apply krtay hyn wo Admission Form per Account wise
Print krna hay.**
Bhai jan jo wasooli ki ho wo print krna hay

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Not Working at all

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test
