### ISSUE TITLE
Contract Deaulter List

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#327]
@nawabanjum @Hammadshahid170 
jin Clients ka bill 00 ya Minus myn hota hy wo b defaulter list myn show hotay hyn aur un ko b Bill Payment ka reminder SMS jata hay. Jo k nahi jana chahiay.
![Untitled](https://user-images.githubusercontent.com/29690582/62602381-0ddfe080-b90d-11e9-80a5-c7f7066521f9.jpg)
![1](https://user-images.githubusercontent.com/29690582/62602383-0ddfe080-b90d-11e9-8414-2dc71d9c2914.jpg)

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test
