### ISSUE TITLE
Group Rights Screens

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#328]
@serviceproviderpk @nawabanjum 
Some screens are missing in AVAILABLE RIGHTS to assign to a group. Plz add them

**Comment by Hammadshahid170** [comment]
@tariqmtoor sir plz mention these screens which are missing

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Left Side Menu myn jitnay sub-Menu show ho rhay hyn sab ki screens k Rights honay chahiayn ta k jo screen kisi ki assign krni ho ki ja sakay.

**Comment by tariqmtoor** [comment]
@serviceproviderpk 
Bhai Jan. This screen belongs to u. Plz work on it immediatly. 
Boht say menu aisay hyn jin k rights manage krnay ki option RIGHTS SCREENS per mojod nahi. jaisa k BIRTHDAY SCREEN.
Aur boht say rights aisay available hyn jin ki screens mojod nahi TEST TYPE, POLICY, VOUCHER TYPE etc. 
Plz Add/Remove the required/Fazool Rights

**Comment by tariqmtoor** [comment]
@serviceproviderpk @Hammadshahid170 @nawabanjum 
![Rights Screen](https://user-images.githubusercontent.com/29690582/65386524-466d3980-dd56-11e9-8fa0-2a2e619abb83.jpg)
[Rights Screen.xlsx](https://github.com/serviceproviderpk/SGS/files/3639667/Rights.Screen.xlsx)

**Comment by tariqmtoor** [comment]
@Hammadshahid170 @serviceproviderpk @TahirHussai @nawabanjum 
jo group branch ny khud create kiy hyn wo b un ko show nhi ho rhay. branch mazeed group b create nhi kr pa rhi. Plz check immediately
