### ISSUE TITLE
Title on Bar

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#329]
![111](https://user-images.githubusercontent.com/29690582/63215806-59805e80-c145-11e9-89ab-67d679e3483e.jpg)

We have 6 domains. If all are open in a same browser it is difficult to find required domain. So, plz edit the title of each domain. Title must be shown as

Stars School
Stars College
Stars Academy
United Academy
Software
Cantab

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test
