### ISSUE TITLE
Fee issue in Discount type

### ISSUE THREAD

**Issue by nawabanjum** [serviceproviderpk/SGS#331]
There is an issue on student discount type ,if we apply the discount in percentage still its calculating flat,

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
%Age Not Working

**Comment by Hammadshahid170** [comment]
@nawabanjum sir locally done

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir plz test

**Comment by tariqmtoor** [comment]
@Hammadshahid170 
Contact Info Report myn %Age Discount walay student ki monthly fee theek show nahi ho rahi.

**Comment by tariqmtoor** [comment]
@nawabanjum @Hammadshahid170 
If we apply DISCOUNT TYPE on a student, then CONTACT INFO REPORT does not show his actual fee

**Comment by Hammadshahid170** [comment]
@tariqmtoor  now if ok then close plz
