### ISSUE TITLE
1- Upgrade Students Screen in APPLY COMMON OPERATION

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#342]
APPLY COMMON OPERATION Screen per Student ko upgrade krtay waqat usi screen per us ka new discount apply krnay ki saholat ho. 
![111](https://user-images.githubusercontent.com/29690582/66369144-9f72d980-e9b4-11e9-96de-78bcd07883f1.png)

**Comment by TahirHussai** [comment]
APPLY COMMON OPERATION Screen per Student ko upgrade krtay waqat usi screen per us ka new discount apply krnay ki saholat ho.
********************************************Fixed****************************************
