### ISSUE TITLE
Important task

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SGS#350]
on login page if user enter invalid username and password, on submit please preserve user name and password in textboxes
![image](https://user-images.githubusercontent.com/19146254/67594101-0c3fef00-f77d-11e9-9e56-6059ce816faf.png)

**Comment by serviceproviderpk** [comment]
2)  change this message "My Support Code is: STARSSCHOOL6361 BranchId=29245"

to

"My Support Code is: STARSSCHOOL6361-29245"

we need to replace "BranchId=" with "-"

**Comment by serviceproviderpk** [comment]
3) remove extra spaces, in table text must be left align
![image](https://user-images.githubusercontent.com/19146254/67594951-ef0c2000-f77e-11e9-8604-0c30c06565f9.png)

**Comment by serviceproviderpk** [comment]
4) use Rs. where we are showing amount/fee

![image](https://user-images.githubusercontent.com/19146254/67595073-35fa1580-f77f-11e9-959c-514625568870.png)

**Comment by Hammadshahid170** [comment]
@serviceproviderpk  done 2,3,4 
i dont understand (1)
