### ISSUE TITLE
Super Admin Report

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#355]
@Hammadshahid170 
Plz UPDATE the existing super admin report as given below

[Admin Report.pdf](https://github.com/serviceproviderpk/SGS/files/3867372/Admin.Report.pdf)

**Comment by Hammadshahid170** [comment]
Show selected Date Report of Super Admin
Change Heading of Report and UI 
1-Add Column of actual monthly fee of branch
2 Add Column of Result lists Sent Today Of branch
3-Add Column SMS Sent Today of Branch 
4-Add Column Collection of Current Month of branch

**Comment by TahirHussai** [comment]
Show selected Date Report of Super Admin
Change Heading of Report and UI
1-Add Column of actual monthly fee of branch
2 Add Column of Result lists Sent Today Of branch
3-Add Column SMS Sent Today of Branch
4-Add Column Collection of Current Month of branch
***********************************************Fixed*********************************************
