### ISSUE TITLE
Tasks Discussed with Tahir sb on 10-02-20

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SGS#368]
1-	**Contract Customers List myn sirf active customers show hotay hyn. All show honay chahiay**

2-	Rights Auto Select on New Branch creation. Group Name must be changed
a.	Organization k Rights myn sy “Import Data From Excel” remove krna hay
b.	“Main Branch” Group ka name “Management Staff” kr dyn. Un k by defaults Rights myn say: Import Data from Excel” remove kr dyn aur neechay walay rights by default add hon:
i.	87
ii.	88
iii.	89
iv.	90
v.	91
vi.	92
vii.	95
viii.	96
ix.	97
x.	98
xi.	99
xii.	100
xiii.	102
c.	“Staff” ko rename kr dyn “Reception”

3-	**Language correction in Fee Generate Bubble**
            It seems that Fee of “Month” is not generated yet. Please Generate it.
4-	New Branch ki SMS ki setting krtay huay password visible hota hay. Nahi hona chahiay.
5-	**Result Entry Screen Result Enter krnay k baad reload honi chahiay.**
6-	Ledger of Schools (Sample Ledger is attached)
7-	Fee History of Students (Sample Ledger is attached)
8-	Delete Button removal from Class Configuration
9-	**Contract SMS Log must be same as Branch sms log**
10-	Branch delete krnay per agreement khud bakhud delete ho jata hay. (Discuss it with Seniors)

**Comment by tariqmtoor** [comment]
Sample Ledger
[Campus Manager Ledger.pdf](https://github.com/serviceproviderpk/SGS/files/4179346/Campus.Manager.Ledger.pdf)

**Comment by tariqmtoor** [comment]
1. Abhi b Sirf active branches ki tadad show ho rahi hay Customers list myn

**Comment by Hammadshahid170** [comment]
@tariqmtoor  sir (It seems that Fee of “Month” is not generated yet. Please Generate it.) same as it add karna hy ?

**Comment by tariqmtoor** [comment]
@serviceproviderpk 
Point # 1, 3 & 4 need ur attention
