### ISSUE TITLE
CantabPublisher.paperMaker

### ISSUE THREAD

**Issue by TahirHussai** [serviceproviderpk/SGS#387]
1.	Jab 2 ya zayada log question enter kr rhay hon tu aksar oqat screen busy jati hay 
2.	Data Base Backup button
3.	Super Access button
4.	Small Roman numbers 
5.	Make Sentences question ki Urdu/Eng dono languages myn formatting nahi hui
6.	Comprehension Paragraph question ko Reading section say nikal k Writing myn lana hay. Jbk Comprehension Paragraph MCQs ko Vice-Versa.
7.	Show latest 100 question in question grid. But must show all questions on demand
8.	Setting in MS Word Doc.
9.	Save as PDF Button
10.	Kia kisi aik chapter ko deactivate krnay per us k questions b deactivate hon gay?

**Comment by tariqmtoor** [comment]
@nawabanjum We have to close this project in this week. Plzzzzzzzzz
